services:
  tailscale:
    build:
      context: ./image/
    container_name: tailscale
    environment:
      TS_AUTH_KEY: ${TS_AUTH_KEY:?err} # from https://login.tailscale.com/admin/settings/authkeys
      TS_HOSTNAME: ${TS_HOSTNAME:-ts-docker}
      TS_STATE_ARG: "/var/lib/tailscale/tailscale.state" # store ts state in a local volume
      TS_SERVE_PORT: ${TS_SERVE_PORT:-}
    volumes:
      - ./ts_data:/var/lib/tailscale/
  myservice:
    image: nginxdemos/hello
    network_mode: "service:tailscale"
