apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
spec:
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      containers:
        - name: tailscale
          image: ghcr.io/lpasselin/tailscale-docker:latest
          env:
            - name: TS_AUTHKEY
              value: "${TS_AUTH_KEY:-err}"
            - name: TS_HOSTNAME
              value: "tailscale-docker-k8s-simple"
            - name: TS_STATE
              value: "mem:"
            - name: TS_SERVE_PORT
              value: "${TS_SERVE_PORT:-}"
            - name: TS_FUNNEL_PORT
              value: "${TS_FUNNEL_PORT:-}"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: nginx
          image: nginxdemos/hello
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
