apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
spec:
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      containers:
        - name: tailscale
          image: ghcr.io/jbowdre/tailscale-docker:latest
          env:
            - name: TS_AUTHKEY
              value: "${TS_AUTHKEY:-err}"
            - name: TS_HOSTNAME
              value: "${TS_HOSTNAME:-ts-docker}"
            - name: TS_STATE_DIR
              value: "/var/lib/tailscale"
            - name: TS_SERVE_PORT
              value: "${TS_SERVE_PORT:-}"
            - name: TS_FUNNEL
              value: "${TS_FUNNEL:-}"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: nginx
          image: nginxdemos/hello
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
